// Package cpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package cpapi

const (
	AgentTokenScopes agentTokenContextKey = "agentToken.Scopes"
)

// BirdConfigResponse defines model for BirdConfigResponse.
type BirdConfigResponse struct {
	ConfigHash string         `json:"configHash"`
	IbgpPeers  []BirdIBGPPeer `json:"ibgpPeers"`
	Node       BirdNodeConfig `json:"node"`
	Policy     BirdPolicy     `json:"policy"`
}

// BirdIBGPPeer defines model for BirdIBGPPeer.
type BirdIBGPPeer struct {
	IsRr         bool   `json:"isRr"`
	LoopbackIpv4 string `json:"loopbackIpv4"`
	LoopbackIpv6 string `json:"loopbackIpv6"`
	NodeId       int    `json:"nodeId"`
	NodeName     string `json:"nodeName"`
}

// BirdNodeConfig defines model for BirdNodeConfig.
type BirdNodeConfig struct {
	Bandwidth          string `json:"bandwidth"`
	BandwidthCommunity string `json:"bandwidthCommunity"`
	ContinentLc        string `json:"continentLc"`
	Id                 int    `json:"id"`
	LoopbackIpv4       string `json:"loopbackIpv4"`
	LoopbackIpv6       string `json:"loopbackIpv6"`
	Name               string `json:"name"`
	RegionCode         int    `json:"regionCode"`
	RegionCommunity    string `json:"regionCommunity"`
	SubregionLc        string `json:"subregionLc"`
	Type               string `json:"type"`
}

// BirdPolicy defines model for BirdPolicy.
type BirdPolicy struct {
	AsPathMaxLen int                     `json:"asPathMaxLen"`
	Communities  *map[string]interface{} `json:"communities,omitempty"`

	// Dn42As MoeNet's DN42 ASN as a STRING (e.g. "4242420998"). The agent's BirdPolicy struct declares this string; sending a JSON number breaks its JSON decode ("cannot unmarshal number into ... of type string").
	Dn42As           string                  `json:"dn42As"`
	Dn42Ipv4Prefix   string                  `json:"dn42Ipv4Prefix"`
	Dn42Ipv6Prefix   string                  `json:"dn42Ipv6Prefix"`
	EbgpExportLimit  int                     `json:"ebgpExportLimit"`
	EbgpImportLimit  int                     `json:"ebgpImportLimit"`
	IbgpExportLimit  int                     `json:"ibgpExportLimit"`
	IbgpImportLimit  int                     `json:"ibgpImportLimit"`
	LargeCommunities *map[string]interface{} `json:"largeCommunities,omitempty"`
	RpkiServers      []RPKIServer            `json:"rpkiServers"`
}

// RPKIServer defines model for RPKIServer.
type RPKIServer struct {
	Host string `json:"host"`
	Name string `json:"name"`
	Port int    `json:"port"`
}

// agentTokenContextKey is the context key for agentToken security scheme
type agentTokenContextKey string
