// Package agentapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package agentapi

const (
	AgentTokenScopes agentTokenContextKey = "agentToken.Scopes"
)

// AggregateStats defines model for AggregateStats.
type AggregateStats struct {
	AvgRtt  float64 `json:"avg_rtt"`
	MaxRtt  float64 `json:"max_rtt"`
	MinRtt  float64 `json:"min_rtt"`
	Samples int     `json:"samples"`
}

// CommunityStats defines model for CommunityStats.
type CommunityStats struct {
	BandwidthDistribution map[string]int `json:"bandwidth_distribution"`
	CryptoDistribution    map[string]int `json:"crypto_distribution"`
	LatencyDistribution   map[string]int `json:"latency_distribution"`
	RegionDistribution    map[string]int `json:"region_distribution"`
	TotalRoutes           int            `json:"total_routes"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// PeerStats defines model for PeerStats.
type PeerStats struct {
	Asn       int64         `json:"asn"`
	Endpoint  string        `json:"endpoint"`
	FailCount int           `json:"fail_count"`
	History   []ProbeResult `json:"history"`

	// LastProbe Unix seconds
	LastProbe  int64   `json:"last_probe"`
	LastRtt    float64 `json:"last_rtt"`
	LastTier   int     `json:"last_tier"`
	ProbeCount int     `json:"probe_count"`

	// Stats Absent (omitted) until there is at least one successful probe.
	Stats *AggregateStats `json:"stats,omitempty"`
}

// ProbeRequest defines model for ProbeRequest.
type ProbeRequest struct {
	// Asn DN42 ASN of the peer to probe (e.g. 4242420998).
	Asn int64 `json:"asn"`
}

// ProbeResult defines model for ProbeResult.
type ProbeResult struct {
	Asn int64 `json:"asn"`

	// Error Present only on failure
	Error       *string `json:"error,omitempty"`
	LatencyTier int     `json:"latency_tier"`
	RttMs       float64 `json:"rtt_ms"`
	Success     bool    `json:"success"`
	Target      string  `json:"target"`

	// Timestamp Unix seconds
	Timestamp int64 `json:"timestamp"`
}

// ToolRequest defines model for ToolRequest.
type ToolRequest struct {
	// Target The tool target. For /ping /tcping /trace /route /path it is an IP/host/prefix (tcping accepts host:port). For /dig it is "<domain> [type]" (space-separated; type defaults to A).
	Target string `json:"target"`
}

// ToolResponse defines model for ToolResponse.
type ToolResponse struct {
	// Result Raw command/BIRD output (plain text).
	Result string `json:"result"`
}

// Err defines model for Err.
type Err = ErrorResponse

// ToolResp defines model for ToolResp.
type ToolResp = ToolResponse

// ToolReq defines model for ToolReq.
type ToolReq = ToolRequest

// agentTokenContextKey is the context key for agentToken security scheme
type agentTokenContextKey string

// DigJSONRequestBody defines body for Dig for application/json ContentType.
type DigJSONRequestBody = ToolRequest

// PathJSONRequestBody defines body for Path for application/json ContentType.
type PathJSONRequestBody = ToolRequest

// PingJSONRequestBody defines body for Ping for application/json ContentType.
type PingJSONRequestBody = ToolRequest

// ProbeNowJSONRequestBody defines body for ProbeNow for application/json ContentType.
type ProbeNowJSONRequestBody = ProbeRequest

// ProbeStatsJSONRequestBody defines body for ProbeStats for application/json ContentType.
type ProbeStatsJSONRequestBody = ProbeRequest

// RouteJSONRequestBody defines body for Route for application/json ContentType.
type RouteJSONRequestBody = ToolRequest

// TcpingJSONRequestBody defines body for Tcping for application/json ContentType.
type TcpingJSONRequestBody = ToolRequest

// TraceJSONRequestBody defines body for Trace for application/json ContentType.
type TraceJSONRequestBody = ToolRequest
